title: "King's College London NLP"
description: "Natural Language Processing Group at King's College London"
url: "https://kclnlp.github.io"
baseurl: ""

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - tmp
  - tmp.html
  - navbar.html
  - README.md
